### ISSUE TITLE
Alternative to providing username and password (import data source file)

### ISSUE THREAD

**Issue by Ulyssys** [Zach-G/MWOMechScraper#1]
The program should be able to take input of a source file (say, the HTML output of the MWOMercs profile page) and utilize it. Not just for security reasons, but also matters of convenience when running it for others or oneself in an offline manner.

Use cases:
* A unit leader may want to have members submit their profiles' HTML, then the leader runs the program on each file to produce a table
* Any user who may not want to break good security practices by putting their credentials into the software

**Comment by Zach-G** [comment]
So, the reason it needs the username and password is because it does more than scrape the HTML of the MWOMercs profile page it also makes GET requests to access specific JSONs. MWOMercs profile page (the HTML) doesn't actually contain any information about the mech's you own. The only page that does is your mech stats page (the one where the tool is gathering all the information about your individual mech stats [matches played, wins, losses, w/l ratio, etc.]). MWOMercs Profile page (the one that shows you the image of the mech's and when you hover over the image it displays the skill points you have allocated to said mech) actually makes a GET request to https://mwomercs.com/mech-collection/data which houses the logged in player's list of owned and not owned mechs. The Profile page doesnt have a table which stores the information (from what I could tell) unlike the mech stats page. When you hover over the image of a mech, the page makes another GET request to https://mwomercs.com/mech-collection/data/stats?mid[]=mechID. If the player owns multiple copies of the 'mech the url will look like https://mwomercs.com/mech-collection/data/stats?mid[0]=mechID&&mid[1]=mechID2&&...&&mid[N]=mechIDN& . This makes it exceedingly difficult (dare I say, impossible?) to gather information about a player's owned mech's name and equipped skill nodes.

I understand that players may not want to put in their user name or password for it to scrape the websites and JSONs, but I don't know of any other way to have the tool access the individual player's JSONs without having them log in. As you will not be able to access the JSON if you have not logged in.

If it were to use source files, a player would need to log into MWOMercs.com and copy their HTML for the mech stats page, and the JSON RAW DATA that is received from the GET request on the Profile page. They would then need to mouse over each mech they own and get the JSON RAW DATA of each mech chassis/variant. This I feel is too much work for a user to do to be able to have it done on an "off-line" mode.

I do however understand the reluctance of putting in your log-in credentials to some random person's program. That is why I have the source code listed along with instructions of how to run the program from the source code and comments about what everything does in the source code, as well as the executable for those who don't want to go through the hassle of setting up Python on their machine. 

If you have any suggestions on how to gather the mech information (owned, chassis/variant, nickname of the mech, and number of skill nodes equipped) without needing to make the GET requests to the JSONs, I'm more than happy to modify the tool further to include an offline mode.

EDIT:
For reference, this is what the HTML of the mech looks like on the Profile Page.
![image](https://user-images.githubusercontent.com/15529828/220792301-c701bf68-ead0-4115-b2fc-366f3ac91e14.png)

EDIT 2:
Links weren't showing "mechID" so I fixed that.

**Comment by Zach-G** [comment]
I am a dunce and now see that the HTML does in fact have the information stored on the HTML.. I'll just need to work further to figure out how to access the specific list items.

Well... maybe not... Here is an example of the HTML of a mech I own (Mist Lynx-D) where you can see that the information has not been populated on the mech because I have not moused over it.
![image](https://user-images.githubusercontent.com/15529828/220793373-dabff892-3d02-4aa5-91ec-e5d47d20a2e9.png)

Here is an image of me showing that I am looking at the correct item and that the HTML has not been populated yet even though I've got it center screen.
![image](https://user-images.githubusercontent.com/15529828/220793580-3c64f097-a268-4451-98b2-83be011bd76a.png)

And then this is the HTML after I mouse over the Mist Lynx.
![image](https://user-images.githubusercontent.com/15529828/220793696-103db31a-c7cc-408d-b8d4-6cf2e7db3e64.png)

So yea.. I don't believe the entries are generated in the HTML until a player mouses over the mech.

However, once all the mech's have been moused over, their entries are stored in the HTML. I could work on an off-line mode for the tool so that players who are worried about putting their information in may have an alternate method to get the information. It would just require that the user mouse over every mech they own and double check that the entries have been made in the HTML.

**Comment by Ulyssys** [comment]
No worries. I think that even if the info were only available in the JSON, I think asking the user to do the small effort of downloading it (to the extent that it's doable without automation) to get the file needed to work on is still a good backup option. For my own purposes being able to see/run the script from source is good (though I haven't looked at it yet, just excited to see such a tool that I was interested in!).

**Comment by Zach-G** [comment]
I am going to leave this issue as open until I make an offline variant of the tool. It may take some time but it's not entirely as impossible as I believed.

Thank you for raising the issue :)

**Comment by the-real-grinny** [comment]
I'm happy to help out with this one. @Zach-G 

I'll do a fork and PR it in when I get to that.

**Comment by Zach-G** [comment]
@the-real-grinny Thank you. 
May I ask for your discord so that we may better communicate?
